### ISSUE TITLE
Row 118 -   tjbotcz_lite/tjbotcz_lite.js 

### ISSUE THREAD

**Issue by mclellanpj** [tjbotcz/tjbotcz_lite#4]
Hi -  I am getting a syntax error /home/pi/Desktop/tjbotcz_lite/tjbotcz_lite.js:118
<<<<<<< HEAD

SyntaxError: Unexpected token <<
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)

Any idea what is causing this?

Pete

**Comment by tjbotcz** [comment]
Hi Pete,

thank you for your notice, your issue is fixed now.

If you encounter any issues, do not hesitate to contact us.

Best regards,
Linette

**Comment by mclellanpj** [comment]
thanks :->
